####Traer peliculas
GET http://localhost:3000/peliculas

###Traer una pelicula por ID
GET http://localhost:3000/peliculas/28982da3-6825-4bf6-984e-fd847cf6e5bd

###Traer peliculas de un Genero en Particular
GET http://localhost:3000/peliculas?genre=Romance

###Crear una pelicula
POST http://localhost:3000/peliculas
Content-Type: application/json

{
    "title": "El padrino",
    "year" : 1975,
    "director": "Francis Copola",
    "duration": 175,
    "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
    "genre": ["Crime", "Drama"],
    "rate": 10
}

###Actualizar una pelicula
PATCH http://localhost:3000/peliculas/31211b62-0b1d-4949-aa28-295179a3b9a0
Content-Type: application/json

{
    "anio": 2000
}

###Eliminar pelicula
DELETE http://localhost:3000/peliculas/28982da3-6825-4bf6-984e-fd847cf6e5bd
